const cloudinary = require(cloudinary);
var cloudinary = require(cloudinary).v2;

function upload(){
    cloudinary.config({
        cloud_name: 'pictureofbots',
        api_key: '123146783337381',
        api_secret: 'lNSZHRwJJ5vprS25VBscSUy2Fe4'
    });
    cloudinary.uploader.upload(file, { tags: 'basic_sample' }, function (err, image) {
        console.log();
        console.log("** File Upload");
        if (err) { console.warn(err); }
        console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
        console.log("* " + image.public_id);
        console.log("* " + image.url);
        waitForAllUploads("pizza", err, image);
      });

}

function waitForAllUploads(id, err, image) {
    uploads[id] = image;
    var ids = Object.keys(uploads);
    if (ids.length === 6) {
      console.log();
      console.log('**  uploaded all files (' + ids.join(',') + ') to cloudinary');
      performTransformations();
    }
  }

exports.upload = upload